### ISSUE TITLE
No Registration -> more participation

### ISSUE THREAD

**Issue by xiriloj-installlinux** [DecentralizedCAN/CAN#6]
Always hate to register for a new service: get a new trash mail, username, password.
I made a bug report, I would like to test, if the same problem is in firefox, but therefor i need to copy the credentials and my name. It would be a lot easier, if I could just copy the url and could try things out without creating an account.

Many people (including me)  dont like to always make new accounts, we want to see, if a service is worth to register for.

If you want more participation and more recognition of your plattform, enable anonymously Read & Write.

**Comment by DecentralizedCAN** [comment]
Thanks for the suggestion. I think I may allow anonymous reading but not
writing. What do you think of that?

**Comment by xiriloj-installlinux** [comment]
Better than nothing.
You dont want to allow anonymous writing because you would have to modify a lot in your code or because you fear spam?

**Comment by DecentralizedCAN** [comment]
Both but I designed it that way to prevent spam.

**Comment by xiriloj-installlinux** [comment]
Okay, i fully understand that you dont want to rewrite some code. 
Its always nice to have options. So I could first enable anonymous writing, to increase participation and if I notice Spam I could  disable anonymous writing. Just as an idea for the future.

**Comment by DecentralizedCAN** [comment]
By anonymous writing, do you mean you would still need an account, but you
could hide your username? Seems pointless to me since usernames are already
anonymous. The only way it could be more anonymous was if the user wasn't
even saved in the db, so there would be no way for an admin to see who
wrote a comment. But I'm not sure if that's worth giving up the ability to
keep track of who's talking to who in a conversation, and the ability to
tag users in comments.
